# Provided by Jan Schoenholz
# Under CC0
# https://github.com/schoenja

image: jasch/openjdk8-javafx:latest

stages:
  - build
  - javadoc
  - test
  - quality_assurance

before_script:
  - chmod u+x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_job:
  tags:
    - cs108
  stage: build
  script:
    - ./gradlew clean jar
  dependencies: []
  artifacts:
    name: "jar-${CI_COMMIT_REF_NAME}"
    paths:
      - build/libs
    expire_in: 2 days
    when: on_success

javadoc:
  tags:
    - cs108
  stage: javadoc
  script:
    - ./gradlew javadoc
  dependencies: []
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - build/docs/javadoc
    expire_in: 2 days
    when: on_success

unit_tests:
  tags:
    - cs108
  stage: test
  script:
    - ./gradlew test jacocoTestReport
    - "echo -n \"Coverage: \" && grep -Eo \"Total.*?([0–9]{1,3})%\" build/reports/jacoco/test/html/index.html | sed \"s/%.*/%/;s/.*>//ge;\""
  coverage: '/Coverage: \d+\%/'
  dependencies: []
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - build/reports/tests/test
      - build/test-results/test
    expire_in: 2 days
    when: on_failure

checkstyle:
  tags:
    - cs108
  stage: quality_assurance
  script:
    - ./gradlew checkstyleMain checkstyleTest
  dependencies: []
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - build/reports/checkstyle
    expire_in: 2 days
    when: on_failure
